# Generated by Django 4.2.7 on 2024-05-26 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0002_userprofile_upgrade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bot_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_bot_collect',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
