# Generated by Django 4.2.7 on 2024-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0003_userprofile_bot_level_userprofile_last_bot_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='character',
            field=models.CharField(default='hamster', max_length=50),
        ),
    ]
