# Generated by Django 4.2.7 on 2024-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0004_userprofile_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='character_bonus',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
